# This rule is not used by the project kubeauth itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.www.seetlabs.kr.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeauth
    app.kubernetes.io/managed-by: kustomize
  name: kubeauth-editor-role
rules:
- apiGroups:
  - apps.www.seetlabs.kr
  resources:
  - kubeauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.www.seetlabs.kr
  resources:
  - kubeauths/status
  verbs:
  - get
