---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.www.seetlabs.kr
  resources:
  - kubeauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.www.seetlabs.kr
  resources:
  - kubeauths/finalizers
  verbs:
  - update
- apiGroups:
  - apps.www.seetlabs.kr
  resources:
  - kubeauths/status
  verbs:
  - get
  - patch
  - update
